### ISSUE TITLE
Add support for other architectures

### ISSUE THREAD

**Issue by JayNewstrom** [rharter/docker-goaccess-cloudfront#11]
When launching the container I get `standard_init_linux.go:207: exec user process caused "exec format error"`

I'm specifically looking for `linux/arm64`

I've solved this in personal containers by using buildx

See https://github.com/JayNewstrom/AwsS3GpgBackup/blob/master/.github/workflows/push_to_dockerhub.yml#L22

I'd be happy to contribute build support if you're interested.

**Comment by JayNewstrom** [comment]
I'm on a Pi4 32 bit. 

```
$ getconf LONG_BIT
32
$ uname -m
armv7l
```

In order to get this to build locally, I had to make a few changes: 
- I had to change the build container to use `alpine:3.12` instead of `alpine:edge`. Something to do with time, I'm not really sure why.
- I had to change the published container to use `oznu/s6-alpine:3.12-armhf` instead of `oznu/s6-alpine:3.12`.

These 2 small changes allowed me to build/deploy locally, and everything is working fine.

**Comment by rharter** [comment]
I haven't tried running this on an Arm device, but I think it's definitely a worthwhile change to support if you want to submit a PR.
GitHub <notifications@github.com> wrote:
“I'm on a Pi4 32 bit.

$ getconf LONG_BIT
32
$ uname -m
armv7l

In order to get this to build locally, I had to make a few changes:

• I had to change the build container to use alpine:3.12 instead of alpine:edge. Something to do with time, I'm not really sure why.
• I had to change the published container to use oznu/s6-alpine:3.12-armhf instead of oznu/s6-alpine:3.12.

These 2 small changes allowed me to build/deploy locally, and everything is working fine.”

**Comment by JayNewstrom** [comment]
So I think the biggest change would be in publishing right now you're using a github action to do publishing, and I'd propose using a different one (https://github.com/crazy-max/ghaction-docker-buildx).

The other change (which should have basically no impact), would be to change the base image to one that's published with a [manifest](https://docs.docker.com/engine/reference/commandline/manifest/) (allowing for publishing for multiple images under a single tag). And the image I've found success with is https://github.com/crazy-max/docker-alpine-s6

Are you okay with those 2 changes @rharter?
